import Quickshell
import Quickshell.Io
import QtQuick

// Watches ~/.config/quickshell/colors.json (generated by matugen) and exposes
// live-updating color properties. When matugen runs (triggered by wallpaper
// change), the FileView hot-reloads and all bindings update automatically.

pragma Singleton

Item {
    id: root

    property color accent:        "#8ab4f8"
    property color accentDim:     "#283b5b"
    property color accentOnDim:   "#c0d8ff"
    property color bgBase:        "#1f1f23"
    property color bgSurface:     "#2b2d30"
    property color bgElevated:    "#3c4043"
    property color bgHover:       "#4a4e52"
    property color textPrimary:   "#e8eaed"
    property color textSecondary: "#9aa0a6"
    property color danger:        "#f28b82"
    property color success:       "#81c995"
    property color outline:       "#6b7280"

    readonly property string fontMain: "SF Pro Rounded"
    readonly property string fontIcon: "JetBrainsMono Nerd Font"

    readonly property int radiusSmall:  8
    readonly property int radiusMedium: 16
    readonly property int radiusLarge:  24
    readonly property int radiusPill:   999

    // --- Color file watcher ---
    FileView {
        id: colorFile
        path: "/home/zafran/.config/quickshell/colors.json"
        watchChanges: true
        onTextChanged: root._parseColors(colorFile.text)
    }

    Component.onCompleted: {
        if (colorFile.text && colorFile.text.length > 5)
            root._parseColors(colorFile.text);
    }

    function _parseColors(jsonText) {
        try {
            let obj = JSON.parse(jsonText);
            if (obj.accent)        root.accent        = obj.accent;
            if (obj.accentDim)     root.accentDim     = obj.accentDim;
            if (obj.accentOnDim)   root.accentOnDim   = obj.accentOnDim;
            if (obj.bgBase)        root.bgBase        = obj.bgBase;
            if (obj.bgSurface)     root.bgSurface     = obj.bgSurface;
            if (obj.bgElevated)    root.bgElevated    = obj.bgElevated;
            if (obj.bgHover)       root.bgHover       = obj.bgHover;
            if (obj.textPrimary)   root.textPrimary   = obj.textPrimary;
            if (obj.textSecondary) root.textSecondary = obj.textSecondary;
            if (obj.danger)        root.danger        = obj.danger;
            if (obj.success)       root.success       = obj.success;
            if (obj.outline)       root.outline       = obj.outline;
        } catch (e) { /* invalid JSON, keep defaults */ }
    }
}
